import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useState } from "react";
import { Card, CardContent, CardHeader, CardTitle } from "../components/ui/card";
import { Button } from "../components/ui/button";
import { Input } from "../components/ui/input";
import { MessageCircle, Phone, Video, UserPlus, Search, Sparkles } from "lucide-react";
import { users, currentUser } from "../data/mockData";
import { Badge } from "../components/ui/badge";
import { Link } from "react-router";
export function Connections() {
    const [searchTerm, setSearchTerm] = useState("");
    const [activeTab, setActiveTab] = useState("connections");
    const connectedUsers = users.filter(u => u.isConnected);
    const suggestedUsers = users.filter(u => !u.isConnected);
    const filteredUsers = (activeTab === "connections" ? connectedUsers : suggestedUsers).filter((user) => user.name.toLowerCase().includes(searchTerm.toLowerCase()) ||
        user.interests.some(interest => interest.toLowerCase().includes(searchTerm.toLowerCase())));
    const getMatchingInterests = (user) => {
        return user.interests.filter(interest => currentUser.interests.includes(interest));
    };
    return (_jsxs("div", { className: "p-8 max-w-6xl mx-auto", children: [_jsxs("div", { className: "mb-8", children: [_jsx("h1", { className: "text-4xl mb-2", children: "Connections" }), _jsx("p", { className: "text-xl text-gray-600", children: "Connect with friends who share your interests" })] }), _jsxs("div", { className: "grid grid-cols-1 md:grid-cols-3 gap-4 mb-8", children: [_jsx(Card, { children: _jsx(CardContent, { className: "pt-6", children: _jsxs("div", { className: "flex items-center justify-between", children: [_jsxs("div", { children: [_jsx("p", { className: "text-sm text-gray-600", children: "Total Connections" }), _jsx("p", { className: "text-3xl mt-1", children: connectedUsers.length })] }), _jsx(MessageCircle, { className: "w-10 h-10 text-amber-600" })] }) }) }), _jsx(Card, { children: _jsx(CardContent, { className: "pt-6", children: _jsxs("div", { className: "flex items-center justify-between", children: [_jsxs("div", { children: [_jsx("p", { className: "text-sm text-gray-600", children: "Suggested Matches" }), _jsx("p", { className: "text-3xl mt-1", children: suggestedUsers.length })] }), _jsx(Sparkles, { className: "w-10 h-10 text-amber-600" })] }) }) }), _jsx(Card, { children: _jsx(CardContent, { className: "pt-6", children: _jsxs("div", { className: "flex items-center justify-between", children: [_jsxs("div", { children: [_jsx("p", { className: "text-sm text-gray-600", children: "Shared Interests" }), _jsx("p", { className: "text-3xl mt-1", children: currentUser.interests.length })] }), _jsx(UserPlus, { className: "w-10 h-10 text-amber-600" })] }) }) })] }), _jsx(Card, { className: "mb-6", children: _jsx(CardContent, { className: "pt-6", children: _jsxs("div", { className: "flex flex-col md:flex-row gap-4 items-center justify-between", children: [_jsxs("div", { className: "flex gap-2 w-full md:w-auto", children: [_jsxs(Button, { variant: activeTab === "connections" ? "default" : "outline", className: activeTab === "connections" ? "bg-amber-600 hover:bg-amber-700" : "", onClick: () => setActiveTab("connections"), children: ["My Connections (", connectedUsers.length, ")"] }), _jsxs(Button, { variant: activeTab === "suggestions" ? "default" : "outline", className: activeTab === "suggestions" ? "bg-amber-600 hover:bg-amber-700" : "", onClick: () => setActiveTab("suggestions"), children: ["Suggestions (", suggestedUsers.length, ")"] })] }), _jsxs("div", { className: "relative w-full md:w-96", children: [_jsx(Search, { className: "absolute left-3 top-1/2 transform -translate-y-1/2 w-4 h-4 text-gray-400" }), _jsx(Input, { placeholder: "Search by name or interests...", value: searchTerm, onChange: (e) => setSearchTerm(e.target.value), className: "pl-10" })] })] }) }) }), _jsx("div", { className: "grid grid-cols-1 md:grid-cols-2 gap-6", children: filteredUsers.map((user) => {
                    const matchingInterests = getMatchingInterests(user);
                    return (_jsx(Card, { className: "hover:shadow-lg transition-shadow", children: _jsx(CardContent, { className: "pt-6", children: _jsxs("div", { className: "flex gap-4", children: [_jsx(Link, { to: `/profile/${user.id}`, children: _jsx("img", { src: user.avatar, alt: user.name, className: "w-20 h-20 rounded-full object-cover cursor-pointer hover:opacity-80 transition-opacity" }) }), _jsxs("div", { className: "flex-1", children: [_jsxs("div", { className: "flex items-start justify-between mb-2", children: [_jsxs("div", { children: [_jsx(Link, { to: `/profile/${user.id}`, children: _jsx("h3", { className: "text-xl font-medium hover:text-amber-600 cursor-pointer", children: user.name }) }), _jsxs("p", { className: "text-sm text-gray-600", children: [user.age, " years \u2022 ", user.location] })] }), activeTab === "suggestions" && matchingInterests.length > 0 && (_jsxs(Badge, { className: "bg-green-100 text-green-700", children: [matchingInterests.length, " matches"] }))] }), _jsx("p", { className: "text-sm text-gray-700 mb-3", children: user.bio }), _jsxs("div", { className: "mb-4", children: [_jsx("p", { className: "text-xs text-gray-600 mb-2", children: "Interests:" }), _jsx("div", { className: "flex flex-wrap gap-1", children: user.interests.map((interest) => {
                                                            const isMatching = currentUser.interests.includes(interest);
                                                            return (_jsx(Badge, { variant: isMatching ? "default" : "secondary", className: isMatching ? "bg-amber-600" : "", children: interest }, interest));
                                                        }) })] }), activeTab === "connections" ? (_jsxs("div", { className: "flex gap-2", children: [_jsx(Link, { to: `/chat/${user.id}`, className: "flex-1", children: _jsxs(Button, { variant: "outline", className: "w-full", children: [_jsx(MessageCircle, { className: "w-4 h-4 mr-2" }), "Message"] }) }), _jsx(Button, { variant: "outline", size: "icon", children: _jsx(Phone, { className: "w-4 h-4" }) }), _jsx(Button, { variant: "outline", size: "icon", children: _jsx(Video, { className: "w-4 h-4" }) })] })) : (_jsxs("div", { className: "flex gap-2", children: [_jsxs(Button, { className: "flex-1 bg-amber-600 hover:bg-amber-700", children: [_jsx(UserPlus, { className: "w-4 h-4 mr-2" }), "Connect"] }), _jsx(Link, { to: `/profile/${user.id}`, children: _jsx(Button, { variant: "outline", children: "View Profile" }) })] }))] })] }) }) }, user.id));
                }) }), filteredUsers.length === 0 && (_jsx(Card, { children: _jsxs(CardContent, { className: "pt-6 text-center py-12", children: [_jsx(Search, { className: "w-16 h-16 text-gray-400 mx-auto mb-4" }), _jsxs("p", { className: "text-lg text-gray-600", children: ["No ", activeTab === "connections" ? "connections" : "suggestions", " found"] }), _jsx("p", { className: "text-sm text-gray-500 mt-2", children: searchTerm ? "Try adjusting your search terms" : "Check back later for new suggestions" })] }) })), activeTab === "suggestions" && filteredUsers.length > 0 && (_jsxs(Card, { className: "mt-8", children: [_jsx(CardHeader, { children: _jsxs(CardTitle, { className: "flex items-center gap-2", children: [_jsx(Sparkles, { className: "w-5 h-5 text-amber-600" }), "How AI Makes Suggestions"] }) }), _jsx(CardContent, { children: _jsxs("div", { className: "space-y-3 text-sm", children: [_jsxs("div", { className: "flex gap-3", children: [_jsx("div", { className: "w-2 h-2 bg-amber-600 rounded-full mt-1.5 flex-shrink-0" }), _jsxs("div", { children: [_jsx("p", { className: "font-medium mb-1", children: "Shared Interests" }), _jsx("p", { className: "text-gray-600", children: "AI analyzes your journal entries to identify your hobbies and interests, then matches you with others who share them." })] })] }), _jsxs("div", { className: "flex gap-3", children: [_jsx("div", { className: "w-2 h-2 bg-amber-600 rounded-full mt-1.5 flex-shrink-0" }), _jsxs("div", { children: [_jsx("p", { className: "font-medium mb-1", children: "Geographic Proximity" }), _jsx("p", { className: "text-gray-600", children: "Connects you with people in your area for easier in-person meetups." })] })] }), _jsxs("div", { className: "flex gap-3", children: [_jsx("div", { className: "w-2 h-2 bg-amber-600 rounded-full mt-1.5 flex-shrink-0" }), _jsxs("div", { children: [_jsx("p", { className: "font-medium mb-1", children: "Activity Patterns" }), _jsx("p", { className: "text-gray-600", children: "Suggests connections with similar daily routines and activity levels." })] })] })] }) })] }))] }));
}
//# sourceMappingURL=Connections.js.map