import { jsx as _jsx, jsxs as _jsxs, Fragment as _Fragment } from "react/jsx-runtime";
import { useParams, Link } from "react-router";
import { Card, CardContent, CardHeader, CardTitle } from "../components/ui/card";
import { Button } from "../components/ui/button";
import { Badge } from "../components/ui/badge";
import { MapPin, Calendar, Heart, MessageCircle, UserPlus, Edit } from "lucide-react";
import { users, currentUser, journalEntries, happyMoments } from "../data/mockData";
export function Profile() {
    const { userId } = useParams();
    const user = userId ? users.find(u => u.id === userId) : currentUser;
    const isCurrentUser = !userId || userId === currentUser.id;
    if (!user) {
        return (_jsx("div", { className: "p-8 max-w-4xl mx-auto", children: _jsx(Card, { children: _jsx(CardContent, { className: "pt-6 text-center py-12", children: _jsx("p", { className: "text-lg text-gray-600", children: "User not found" }) }) }) }));
    }
    return (_jsxs("div", { className: "p-8 max-w-5xl mx-auto", children: [_jsx(Card, { className: "mb-8", children: _jsx(CardContent, { className: "pt-6", children: _jsxs("div", { className: "flex flex-col md:flex-row gap-6", children: [_jsx("img", { src: user.avatar, alt: user.name, className: "w-32 h-32 rounded-full object-cover" }), _jsxs("div", { className: "flex-1", children: [_jsxs("div", { className: "flex items-start justify-between mb-4", children: [_jsxs("div", { children: [_jsx("h1", { className: "text-3xl mb-2", children: user.name }), _jsxs("div", { className: "flex flex-wrap gap-4 text-gray-600", children: [_jsxs("div", { className: "flex items-center gap-2", children: [_jsx(Calendar, { className: "w-4 h-4" }), _jsxs("span", { children: [user.age, " years old"] })] }), _jsxs("div", { className: "flex items-center gap-2", children: [_jsx(MapPin, { className: "w-4 h-4" }), _jsx("span", { children: user.location })] })] })] }), isCurrentUser ? (_jsxs(Button, { variant: "outline", children: [_jsx(Edit, { className: "w-4 h-4 mr-2" }), "Edit Profile"] })) : (_jsx("div", { className: "flex gap-2", children: user.isConnected ? (_jsx(Link, { to: `/chat/${user.id}`, children: _jsxs(Button, { className: "bg-amber-600 hover:bg-amber-700", children: [_jsx(MessageCircle, { className: "w-4 h-4 mr-2" }), "Message"] }) })) : (_jsxs(Button, { className: "bg-amber-600 hover:bg-amber-700", children: [_jsx(UserPlus, { className: "w-4 h-4 mr-2" }), "Connect"] })) }))] }), _jsx("p", { className: "text-lg text-gray-700 mb-4", children: user.bio }), _jsxs("div", { children: [_jsx("p", { className: "text-sm text-gray-600 mb-2", children: "Interests:" }), _jsx("div", { className: "flex flex-wrap gap-2", children: user.interests.map((interest) => {
                                                    const isShared = !isCurrentUser && currentUser.interests.includes(interest);
                                                    return (_jsxs(Badge, { variant: isShared ? "default" : "secondary", className: isShared ? "bg-amber-600" : "", children: [interest, isShared && " ✓"] }, interest));
                                                }) })] })] })] }) }) }), isCurrentUser && (_jsxs(_Fragment, { children: [_jsxs("div", { className: "grid grid-cols-1 md:grid-cols-3 gap-6 mb-8", children: [_jsxs(Card, { children: [_jsx(CardHeader, { className: "flex flex-row items-center justify-between pb-2", children: _jsx(CardTitle, { className: "text-sm", children: "Journal Entries" }) }), _jsxs(CardContent, { children: [_jsx("div", { className: "text-3xl", children: journalEntries.length }), _jsx("p", { className: "text-xs text-gray-600 mt-1", children: "Total recordings" })] })] }), _jsxs(Card, { children: [_jsx(CardHeader, { className: "flex flex-row items-center justify-between pb-2", children: _jsx(CardTitle, { className: "text-sm", children: "Connections" }) }), _jsxs(CardContent, { children: [_jsx("div", { className: "text-3xl", children: users.filter(u => u.isConnected).length }), _jsx("p", { className: "text-xs text-gray-600 mt-1", children: "Active friends" })] })] }), _jsxs(Card, { children: [_jsx(CardHeader, { className: "flex flex-row items-center justify-between pb-2", children: _jsx(CardTitle, { className: "text-sm", children: "Happy Moments" }) }), _jsxs(CardContent, { children: [_jsx("div", { className: "text-3xl", children: happyMoments.length }), _jsx("p", { className: "text-xs text-gray-600 mt-1", children: "This month" })] })] })] }), _jsxs("div", { className: "grid grid-cols-1 md:grid-cols-2 gap-6", children: [_jsxs(Card, { children: [_jsx(CardHeader, { children: _jsx(CardTitle, { children: "Recent Journal Entries" }) }), _jsx(CardContent, { className: "space-y-3", children: journalEntries.slice(0, 3).map((entry) => (_jsxs("div", { className: "flex gap-3 p-3 bg-gray-50 rounded-lg", children: [_jsx("img", { src: entry.thumbnail, alt: "Journal", className: "w-16 h-16 rounded-lg object-cover" }), _jsxs("div", { className: "flex-1", children: [_jsxs("div", { className: "flex items-center gap-2 mb-1", children: [_jsx("span", { className: "text-sm text-gray-600", children: entry.date.toLocaleDateString() }), _jsx(Badge, { variant: "secondary", className: `text-xs ${entry.mood === 'happy' ? 'bg-green-100 text-green-700' :
                                                                        entry.mood === 'excited' ? 'bg-blue-100 text-blue-700' :
                                                                            'bg-gray-100 text-gray-700'}`, children: entry.mood })] }), _jsx("p", { className: "text-sm text-gray-700 line-clamp-2", children: entry.aiSummary })] })] }, entry.id))) })] }), _jsxs(Card, { children: [_jsx(CardHeader, { children: _jsxs(CardTitle, { className: "flex items-center gap-2", children: [_jsx(Heart, { className: "w-5 h-5 text-rose-500" }), "Happy Moments"] }) }), _jsx(CardContent, { className: "space-y-3", children: happyMoments.slice(0, 3).map((moment) => (_jsxs("div", { className: "p-3 border border-rose-200 bg-rose-50 rounded-lg", children: [_jsxs("div", { className: "flex items-center gap-2 mb-2", children: [_jsx(Badge, { variant: "secondary", className: "text-xs bg-rose-200 text-rose-800", children: moment.source }), _jsx("span", { className: "text-xs text-gray-600", children: moment.date.toLocaleDateString() })] }), _jsx("p", { className: "text-sm", children: moment.description }), moment.conversationWith && (_jsxs("p", { className: "text-xs text-gray-600 mt-2", children: ["With: ", moment.conversationWith] }))] }, moment.id))) })] })] })] })), !isCurrentUser && (_jsxs(Card, { children: [_jsx(CardHeader, { children: _jsxs(CardTitle, { children: ["About ", user.name] }) }), _jsx(CardContent, { children: _jsxs("div", { className: "space-y-4", children: [_jsxs("div", { children: [_jsx("h3", { className: "font-medium mb-2", children: "Interests" }), _jsx("div", { className: "flex flex-wrap gap-2", children: user.interests.map((interest) => (_jsx(Badge, { variant: "secondary", children: interest }, interest))) })] }), _jsxs("div", { children: [_jsx("h3", { className: "font-medium mb-2", children: "Location" }), _jsx("p", { className: "text-gray-700", children: user.location })] }), _jsxs("div", { children: [_jsx("h3", { className: "font-medium mb-2", children: "Bio" }), _jsx("p", { className: "text-gray-700", children: user.bio })] }), user.isConnected && (_jsxs("div", { className: "pt-4 border-t", children: [_jsxs("p", { className: "text-sm text-gray-600 mb-3", children: ["You're connected with ", user.name.split(' ')[0], ". Send a message to start a conversation!"] }), _jsx(Link, { to: `/chat/${user.id}`, children: _jsxs(Button, { className: "w-full bg-amber-600 hover:bg-amber-700", children: [_jsx(MessageCircle, { className: "w-4 h-4 mr-2" }), "Send Message"] }) })] }))] }) })] }))] }));
}
//# sourceMappingURL=Profile.js.map